# TI3 Praktikum 1
# Jason Purnomo
# 17.04.2026
#from unittest import result

marks_14 = ['1', '2', '3', '4']
marks_AE = ['A', 'B', 'C', 'D', 'E']
marks_HM = ['1.0', '1.3', '1.7', '2.0', '2.3', '2.7', '3.0', '3.3', '3.7', '4.0']
NB = 'n.b'
MARKSCALES = {'marks_14': marks_14, 'marks_AE': marks_AE, 'marks_HM': marks_HM}

def point_ladder(hi: int, lo: int) -> list[str]:
	#Diese Funktion erstellt eine Liste von Punkten als Strings, von hi bis lo
	
	"""
	Return an Array of Strings, representing the points from *hi* to *lo*.
	
	Bsp: `point_ladder(5,3)` liefert `['5','4','3']`.
	Es gilt: `hi-lo+1 == len(ret)`
	"""
	return [str(p) for p in range(hi, lo-1, -1)]
	
def mark_ladder(marks: list[str], n: int) -> list[str]:
    #Diese Funktion verteilt die Noten gleichmäßig auf n Punkte-Slots
    #Verteilungsproblem: 5 Slots, 3 Noten -> 5/3 = 1 R 2. 	#--> die schlechteren Noten (hinten) bekommen die Extrapunkte
    """
    Return an Array of Strings, representing evenly distributed marks over *N* bins.

    Raise *Exception* when range is too small for given number of marks 
    (the number of elements in *marks* must be at most *n*)

    Bsp: `mark_ladder(['A','B','C'], 5)` liefert `['A','B','B','C','C']`.
    Es gilt: `n == len(ret)`
    """
    
    if len(marks) > n:
        raise Exception(f"Zu viele Noten ({len(marks)}) für {n} Slots!")

    base = n // len(marks) #// : Ganzzahlige Division
    #Jede Note bekommt mindestens 'base' Slots
    extra = n % len(marks)	# % : Remainder from Division
    #Diese vielen Noten bekommen einen extra Slot

    #extra Slots von HINTEN verteilen (schlechtere Noten zuerst)

    result = []
    for i, mark in enumerate(reversed(marks)):
        slots = base + (1 if i < extra else 0)
        result.extend([mark] * slots)
        
    return list(reversed(result))

def as_dict(marks: list[str], hi: int, lo: int) -> dict:
     #Diese Funktion kombiniert point_ladder und mark_ladder zu einem Dictionary
     """
     Return  *Dict[str, str]* as  `{pt : mark}`.
     Param *marks* is an array of labels
     """
     pts = point_ladder(hi, lo)		#['10', '9', '8', '7', ...]
     mks = mark_ladder(marks, len(pts))		#['A', 'A', 'B', 'B', 'C', 'C', 'D', 'D']
     return dict(zip(pts, mks))

def as_text(marktable) -> str:
     #Diese Funktion gibt das Dictionary als lesbaren Text aus
     #Zeilen mit \n getrennt, Spalten mit \t
     """
     Return *marktable* as text (String of newline-separated lines).
     Param *marktable* is a *Dict[str, str]* as generated by `as_dict()`
     """
     
     lines = [f"{pt}\t{mk}" for pt, mk in marktable.items()]
     return "\n".join(lines)

def getmark(table, pt: str) -> str:
     #Diese Funktion schlägt die Note für einen Punktwert nach
     #3 Fälle:
     #1.) pt = "15" --> Note aus Tabelle
     #2.) pt = "999" --> Bestnote (zu viele Punkte -> Note[0])
     #3.) pt = "1" --> 'n.b' (nicht bestanden)
     """
     Return  mark for *pt* points;
     if *pt* is out of range, yield appropriate either best mark or `'n.b'`.
     Param *table* is a *Dict[str, str]* as generated by `as_dict()`
     """
     if pt in table:
           return table[pt]
     
	 #Außerhalb der Skala: war pt zu hoch oder zu niedrig?
     pts = list(table.keys())
     hi_val = int(pts[0])	#höchster Punktwert
     lo_val = int(pts[-1])	#niedrigster Punktwert
     
     if int(pt) > hi_val:
          return table[pts[0]]	#Bestnote (mehr als nötig)
     else:
          return NB		#n.b. (nicht bestanden)

def mkhisto_lsg(marks):
    count = {}
    for m in marks:
        if count.get(m):
            count[m] += 1
        else:
            count[m] = 1
    return count
def print_histo_lsg(count):
    for m in sorted(count.keys()):
        n = count[m]
        print(f'{m}: {'#' * n}  ({n})')